version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - logpie_logs:/app/logs
    environment:
      - LOG_LEVEL=DEBUG
  prometheus:
    image: prom/prometheus:v2.43.0
    volumes:
      - ./assets/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:9.0.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  logpie_logs:
