masking:
  enabled: true
  rules:
    email:
      pattern: "[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+"
      replacement: "[EMAIL_MASKED]"
      enabled: true
    cpf:
      pattern: "\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}"
      replacement: "[CPF_MASKED]"
      enabled: true
    phone:
        pattern: "\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}"
        replacement: "[PHONE_MASKED]"
        enabled: true
