masking:
  enabled: true
  rules:
    email:
      pattern: "[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+"
      replacement: "***@***.***"
      enabled: true
    cpf:
      pattern: "\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}"
      replacement: "***.***.***-**"
      enabled: true
    phone:
        pattern: "\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}"
        replacement: "(XX) XXXXX-XXXX"
        enabled: true
