masking:
  enabled: true
  rules:
    credit_card:
      pattern: '\d{4}-\d{4}-\d{4}-\d{4}'
      replacement: "[CREDIT_CARD_MASKED]"
      priority: 1
      enabled: true  
    email:
      pattern: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[A-Za-z]{2,}'
      replacement: "[EMAIL_MASKED]"
      priority: 2
      enabled: true
    cpf:
      pattern: '\d{3}\.\d{3}\.\d{3}-\d{2}'
      replacement: "[CPF_MASKED]"
      priority: 3
      enabled: true
    phone:
        pattern: '(\(?\d{2}\)?\s?)?\d{4,5}-\d{4}'
        replacement: "[PHONE_MASKED]"
        priority: 4
        enabled: true
